### ISSUE TITLE
Move prereq cells array outside of rubric section, but keep it backward compatible

### ISSUE THREAD

**Issue by erdogmush** [cmusv/pysheetgrader-core#33]
Since prereq cells apply to all rubric types in the same way, it should be outside the rubric section rather than inside, similar to alt_cells, like this:

```
rubric:
 type: formula
 score: 4
prereq:
 - C1
 - C2
```

Right now it's like this: 

```
rubric:
 type: formula
 score: 4
 prereq:
  - C1
  - C2
```
